name: Compilar Recibo Software Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Obter Codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pillow pyinstaller

    - name: Gerar Executavel com PyInstaller
      run: |
        pyinstaller --clean --noconsole --onefile --collect-all customtkinter --name="ReciboSoftware" main.py

    - name: Publicar Executavel
      uses: actions/upload-artifact@v4
      with:
        name: ReciboSoftware-Windows
        path: dist/ReciboSoftware.exe
